package com.crystalline.aether.models.architecture;

import com.crystalline.aether.models.Config;
import com.crystalline.aether.services.CalculationPlatform;
import com.crystalline.aether.services.utils.BufferUtils;
import com.crystalline.aether.services.world.World;

import java.nio.FloatBuffer;
import java.util.Stack;

public abstract class RealityAspect {
    protected abstract Object[] getState();
    protected abstract void setState(Object[] state);
    public abstract void switchValues(FloatBuffer proposals);
    public abstract FloatBuffer determineUnits(World parent);

    /* Processing functions to be called by World in its main loop */
    public abstract void processUnits(World parent);
    public abstract void processTypes(World parent);
    public abstract void processMechanics(World parent);
    public abstract void postProcess(World parent);

    protected Config conf;
    private final Stack<Object[]> state;
    public RealityAspect(Config conf_){
        conf = conf_;
        state = new Stack<>();
    }
    public void pushState(){
        state.push(getState());
    }
    public void popState(){
        setState(state.pop());
    }

    public static float getOffsetCode(int x, int y, int sizeX, FloatBuffer buffer){
        return BufferUtils.get(x,y,sizeX,Config.bufferCellSize,0, buffer);
    }

    public static void setOffsetCode(int x, int y, int sizeX, FloatBuffer buffer, float value){
        BufferUtils.set(x,y,sizeX,Config.bufferCellSize,0, buffer, value);
    }

    public static float getToApply(int x, int y, int sizeX, FloatBuffer buffer){
        return BufferUtils.get(x,y,sizeX,Config.bufferCellSize,0, buffer);
    }

    public static void setToApply(int x, int y, int sizeX, FloatBuffer buffer, float value){
        BufferUtils.set(x,y,sizeX,Config.bufferCellSize,0, buffer, value);
    }

    public static int getXFromOffsetCode(int x, int code){
        switch(code){
            case 1: case 8: case 7: return (x-1);
            case 2: case 0: case 6: return (x);
            case 3: case 4: case 5: return (x+1);
        }
        return x;
    }
    public static int getYFromOffsetCode(int y, int code){
        switch(code){
            case 7: case 6: case 5: return (y+1);
            case 8: case 0: case 4: return (y);
            case 1: case 2: case 3: return (y-1);
        }
        return y;
    }

    /**
     * Returns a code for the hardcoded directions based on the arguments
     * @param ox offset x -
     * @param oy offset y - the direction to which the direction should point
     * @return a code unique for any direction, generated by the given offsets
     */
    public static int getOffsetCode(int ox, int oy){
        if((ox < 0)&&(oy < 0)) return 1;
        if((ox == 0)&&(oy < 0)) return 2;
        if((ox > 0)&&(oy < 0)) return 3;
        if((ox > 0)&&(oy == 0)) return 4;
        if((ox > 0)/*&&(oy > 0)*/) return 5;
        if((ox == 0)&&(oy > 0)) return 6;
        if((ox < 0)&&(oy > 0)) return 7;
        if((ox < 0)/*&&(oy == 0)*/) return 8;
        return 0;
    }

    public static int getTargetX(int x, int y, int sizeX, FloatBuffer buffer){
        return getXFromOffsetCode(x,(int)getOffsetCode(x,y,sizeX,buffer));
    }

    public static int getTargetY(int x, int y, int sizeX, FloatBuffer buffer){
        return getYFromOffsetCode(y,(int)getOffsetCode(x,y,sizeX,buffer));
    }
}
